# Generated by Django 4.2.4 on 2023-08-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcestag',
            name='resources_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resources'),
        ),
        migrations.AddField(
            model_name='resourcestag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.tag'),
        ),
        migrations.AddField(
            model_name='resources',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='resources.category'),
        ),
        migrations.AddField(
            model_name='resources',
            name='tags',
            field=models.ManyToManyField(through='resources.ResourcesTag', to='resources.tag'),
        ),
        migrations.AddField(
            model_name='resources',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
