# Generated by Django 4.2.4 on 2023-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="resource_id",
            new_name="resources_id",
        ),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="resourcestag",
            constraint=models.UniqueConstraint(
                models.F("resources_id"),
                name="resource_tag_unique",
                violation_error_message="Tag already exist for resources",
            ),
        ),
    ]
