# Generated by Django 4.2.4 on 2023-09-01 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0005_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
